# Generated by Django 5.1.1 on 2025-01-02 10:56

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=50)),
                ('room_url', models.CharField(default='', max_length=10)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=50)),
                ('room_url', models.CharField(default='', max_length=10)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_created_hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_owner', models.CharField(max_length=50)),
                ('hub_name', models.CharField(max_length=100)),
                ('hub_description', models.TextField(blank=True, null=True)),
                ('hub_image', models.CharField(max_length=50, null=True)),
                ('hub_privacy_setting', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('room_url', models.CharField(default=myapp.models.generate_room_url, editable=False, max_length=10, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hub_owner', 'hub_name'), name='unique_hub_per_teacher')],
            },
        ),
        migrations.CreateModel(
            name='Students_joined_hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('hub_owner', models.CharField(default='default_owner', max_length=50)),
                ('hub_url', models.CharField(max_length=10)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapp.teachers_created_hub')),
            ],
        ),
    ]
